name 'chef_desktop'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_desktop'
long_description 'Installs/Configures chef_desktop'
version '0.1.0'
