---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  # guide to create osx boxes https://gist.github.com/rmoriz/37b671afe53c984b2f85
  - name: macosx-10.11
#  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chef_desktop::default]
    attributes:
